version: "3.7"

services:
  flask:
    build:
      context: ./flask
      args:
        - ENV: dev
    container_name: flask
    restart: always
    expose:
      - 5005
    volumes:
      - "/home/irteam/data:/home/irteam/data"
      - "/home/irteam/logs:/home/irteam/logs"
  nginx:
    build:
      context: ./nginx
      args:
        - ENV: dev
    container_name: nginx
    restart: always
    environment:
      - ENV=dev
    ports:
      - "80:80"
    volumes:
      - "/home/irteam/data:/home/irteam/data"
      - "/home/irteam/logs:/home/irteam/logs"