version: "3.7"

services:
  flask:
    build:
      context: ./flask
      args:
        ENV: "release"
    image: pando0314/youtube-downloader-flask
    container_name: flask
    restart: always
    expose:
      - 5005
    volumes:
      - "/home/irteam/data:/home/irteam/data"
      - "/home/irteam/logs:/home/irteam/logs"
  nginx:
    build:
      context: ./nginx
      args:
        ENV: "release"
    image: pando0314/youtube-downloader-nginx
    container_name: nginx
    restart: always
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    volumes:
      - "/home/irteam/data:/home/irteam/data"
      - "/home/irteam/logs:/home/irteam/logs"